// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaLcAPOAiBQOsp60uevsPrXIV4Is6I-0',
    appId: '1:41999204235:web:a27916702b10bb31adf98e',
    messagingSenderId: '41999204235',
    projectId: 'mandirseva-69aa6',
    authDomain: 'mandirseva-69aa6.firebaseapp.com',
    storageBucket: 'mandirseva-69aa6.firebasestorage.app',
    measurementId: 'G-MKNS7Q57Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98sn36xFXyW_tQkgT_L8gjkId-LB7FLg',
    appId: '1:41999204235:android:11311f32c8d148beadf98e',
    messagingSenderId: '41999204235',
    projectId: 'mandirseva-69aa6',
    storageBucket: 'mandirseva-69aa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcEjvgc06Sc715jWVaVhQL4yOKv12BYOE',
    appId: '1:41999204235:ios:864949c746684975adf98e',
    messagingSenderId: '41999204235',
    projectId: 'mandirseva-69aa6',
    storageBucket: 'mandirseva-69aa6.firebasestorage.app',
    iosBundleId: 'com.example.mandirseva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcEjvgc06Sc715jWVaVhQL4yOKv12BYOE',
    appId: '1:41999204235:ios:864949c746684975adf98e',
    messagingSenderId: '41999204235',
    projectId: 'mandirseva-69aa6',
    storageBucket: 'mandirseva-69aa6.firebasestorage.app',
    iosBundleId: 'com.example.mandirseva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfaLcAPOAiBQOsp60uevsPrXIV4Is6I-0',
    appId: '1:41999204235:web:cd0bf904bb539d8cadf98e',
    messagingSenderId: '41999204235',
    projectId: 'mandirseva-69aa6',
    authDomain: 'mandirseva-69aa6.firebaseapp.com',
    storageBucket: 'mandirseva-69aa6.firebasestorage.app',
    measurementId: 'G-MYQH7Z5HF0',
  );
}
