import 'package:flutter/material.dart';
// Firebase Imports ko add kiya gaya hai
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Yeh file 'flutterfire configure' se bani hai

// Import all required screens
import 'package:mandirseva/screens/spash_screen.dart';
import 'package:mandirseva/screens/home_screen.dart';
import 'package:mandirseva/screens/EventsScreen.dart';
import 'package:mandirseva/screens/ScheduleScreen.dart';
import 'package:mandirseva/screens/TempleInfoScreen.dart';
import 'package:mandirseva/screens/booking_screen.dart';
import 'package:mandirseva/screens/notifications_screen.dart';
import 'package:mandirseva/screens/emergency_screen.dart';
import 'package:mandirseva/screens/operator_dashboard.dart';
import 'package:mandirseva/screens/ticket_screen.dart';

// Authentication Screens Import
import 'package:mandirseva/authentication/signin_screen.dart';
import 'package:mandirseva/authentication/signup_screen.dart';
import 'package:mandirseva/authentication/forget_password_screen.dart';


void main() async {
  // 1. Ensure Flutter bindings are initialized before calling native code (like Firebase)
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase using the configuration generated by the FlutterFire CLI
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Agar Firebase initialize hone mein koi error aaye to yahan print hoga
    debugPrint('Firebase Initialization Error: $e');
    // Production app mein yahan ek error screen dikhaya ja sakta hai
  }

  runApp(const MandirSevaApp());
}

class MandirSevaApp extends StatelessWidget {
  const MandirSevaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MandirSeva',
      debugShowCheckedModeBanner: false, // Clean UI ke liye
      theme: ThemeData(
        primarySwatch: Colors.deepOrange,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
        useMaterial3: true,
      ),

      // The application starts at the root route '/'.
      initialRoute: '/',

      routes: {
        // 1. '/' is mapped to the SplashScreen.
        '/': (context) => const SplashScreen(),

        // Authentication Routes
        '/signin': (context) => const SignInScreen(),
        '/signup': (context) => const SignUpScreen(),
        '/forget_password': (context) => const ForgetPasswordScreen(),

        // Main App Routes
        '/home': (context) => const HomeScreen(),
        '/notifications': (context) => const NotificationsScreen(),
        '/operator': (context) => const OperatorDashboard(),
        '/booking': (context) => const BookingScreen(),
        '/emergency': (context) => const EmergencyScreen(),
        '/schedule': (context) => const ScheduleScreen(),
        '/events': (context) => const EventsScreen(),
        '/info': (context) => const TempleInfoScreen(),
      },

      onGenerateRoute: (settings) {
        // Handle routes that require arguments, like the TicketScreen
        if (settings.name == '/ticket') {
          // Expecting the ticket ID as a String argument
          final args = settings.arguments as String?;
          if (args != null) {
            return MaterialPageRoute(
              builder: (_) => TicketScreen(ticketId: args),
            );
          }
        }
        return null; // For any unknown route
      },
    );
  }
}
